using System.Collections.Generic;

namespace EnhancedTextures
{
    public static class TexturesToPatch
    {
        public static Dictionary<string, Dictionary<string, string>> Textures = new Dictionary<string, Dictionary<string, string>>() {
            {"Barrel", new Dictionary<string, string>() { {"_MainTex","BarrelMat"} } },
            {"Birch", new Dictionary<string, string>() { {"_MainTex","BirchTexture"} } },
            {"Boat", new Dictionary<string, string>() { {"_MainTex","BoatTexture"}, {"_BumpMap","BoatTexture_normal"}, {"_OcclusionMap","BoatTexture_displace"} } },
            {"BoatHole", new Dictionary<string, string>() { {"_MainTex","BoatHole"} } },
            {"Cart", new Dictionary<string, string>() { {"_OcclusionMap","Ground026_2K_AmbientOcclusion"} } },
            {"Cave", new Dictionary<string, string>() { {"_MainTex","Ground026_2K_AmbientOcclusion"} } },
            {"CheckeredShirt", new Dictionary<string, string>() { {"_MainTex","CheckeredShirt_0"} } },
            {"ChestBlue", new Dictionary<string, string>() { {"_MainTex","ChestTexture_col_blue"} } },
            {"ChestFree", new Dictionary<string, string>() { {"_MainTex","ChestTexture_col_free"} } },
            {"ChestInteract", new Dictionary<string, string>() { {"_MainTex","ChestTexture_col_green"}  } },
            {"ChestOrange", new Dictionary<string, string>() { {"_MainTex","ChestTexture_col_orange"} } },
            {"ChestWhite", new Dictionary<string, string>() { {"_MainTex","ChestTexture_col_white"} } },
            {"ChestTexture_col_orange", new Dictionary<string, string>() { {"_MainTex", "ChestTexture_col_orange" } } },
            {"Cooking", new Dictionary<string, string>() { {"_MainTex","CookingTexture_col"}, {"_BumpMap", "CookingTexture_Normal"} } },
            {"Core", new Dictionary<string, string>() { {"_MainTex","AncientCore"} } },
            {"Cow", new Dictionary<string, string>() { {"_MainTex","CowTexture"} } },
            {"Crate", new Dictionary<string, string>() { {"_MainTex","Crate"} } },
            {"DarkOak", new Dictionary<string, string>() { {"_MainTex","DarkOak"} } },
            {"Enforcer", new Dictionary<string, string>() { {"_MainTex","Enforcer_0"} } },
            {"Fir", new Dictionary<string, string>() { {"_MainTex","FirTexture"} } },
            {"Fletching", new Dictionary<string, string>() { {"_MainTex","Fletching_texture"} } },
            {"FlintTexture", new Dictionary<string, string>() { {"_MainTex","FlintTexture"} } },
            {"Floor 1", new Dictionary<string, string>() { {"_MainTex","Ground026_2K_Color"}, {"_BumpMap","Ground026_2K_Normal"}, {"_OcclusionMap","Ground026_2K_AmbientOcclusion"} } },
            {"Furnace", new Dictionary<string, string>() { {"_MainTex","Furnace_color"}, {"_BumpMap","Furnace_normal"}, {"_OcclusionMap","Furnace_AO"} } },
            {"Grave", new Dictionary<string, string>() { {"_MainTex","Ground026_2K_AmbientOcclusion"} } },
            {"Guardian", new Dictionary<string, string>() { {"_MainTex","Ground026_2K_AmbientOcclusion"}, {"_OcclusionMap","Ground026_2K_AmbientOcclusion"}, {"_EmissionMap","Guardian_Emission"} } },
            {"Guardian_Blue", new Dictionary<string, string>() { {"_MainTex","Ground026_2K_AmbientOcclusion"}, {"_OcclusionMap","Ground026_2K_AmbientOcclusion"}, {"_EmissionMap","Guardian_Emission"} } },
            {"Guardian_Green", new Dictionary<string, string>() { {"_MainTex","Ground026_2K_AmbientOcclusion"}, {"_OcclusionMap","Ground026_2K_AmbientOcclusion"}, {"_EmissionMap","Guardian_Emission"} } },
            {"Guardian_Pink", new Dictionary<string, string>() { {"_MainTex","Ground026_2K_AmbientOcclusion"}, {"_OcclusionMap","Ground026_2K_AmbientOcclusion"}, {"_EmissionMap","Guardian_Emission"} } },
            {"Guardian_Red", new Dictionary<string, string>() { {"_MainTex","Ground026_2K_AmbientOcclusion"}, {"_OcclusionMap","Ground026_2K_AmbientOcclusion"}, {"_EmissionMap","Guardian_Emission"} } },
            {"Guardian_Yellow", new Dictionary<string, string>() { {"_MainTex","Ground026_2K_AmbientOcclusion"}, {"_OcclusionMap","Ground026_2K_AmbientOcclusion"}, {"_EmissionMap","Guardian_Emission"} } },
            {"Hogoblin", new Dictionary<string, string>() { {"_MainTex","HogoblinTexture"} } },
            {"HorseShoe", new Dictionary<string, string>() { {"_MainTex","Metal011_1K_Color"}, {"_OcclusionMap","Ground026_2K_AmbientOcclusion"} } },
            {"House", new Dictionary<string, string>() { {"_OcclusionMap","Ground026_2K_Color"} } },
            {"Hut", new Dictionary<string, string>() { {"_MainTex","Stairs"} } },
            {"IronBar", new Dictionary<string, string>() { {"_MainTex","Metal011_1K_Color"}, {"_ParallaxMap","Metal011_1K_Color"} } },
            {"Mast", new Dictionary<string, string>() { {"_MainTex","PoleTexture"} } },
            {"Log", new Dictionary<string, string>() { {"_MainTex","LogMat"} } },
            {"Oak", new Dictionary<string, string>() { {"_MainTex","OakTexture"} } },
            {"Ore_Adamantite", new Dictionary<string, string>() { {"_MainTex","OreAdamantite_Color"}, {"_BumpMap","OreGold_Norm"}, {"_OcclusionMap","OreGold_AO"}, {"_ParallaxMap","OreGold_Displ"} } },
            {"Ore_Chunkium", new Dictionary<string, string>() { {"_MainTex","ore_chunkium"}, {"_BumpMap","OreGold_Norm"}, {"_OcclusionMap","OreGold_AO"}, {"_ParallaxMap","OreGold_Displ"} } },
            {"Ore_Gold", new Dictionary<string, string>() { {"_MainTex","OreGold_Color"}, {"_BumpMap","OreGold_Norm"}, {"_OcclusionMap","OreGold_AO"}, {"_ParallaxMap","OreGold_Displ"} } },
            {"Ore_iron", new Dictionary<string, string>() { {"_MainTex","IronTexture"}, {"_OcclusionMap","IronTexture_ambient"} } },
            {"Ore_Mithril", new Dictionary<string, string>() { {"_MainTex","OreMihtril_Color"}, {"_BumpMap","OreGold_Norm"}, {"_OcclusionMap","OreGold_AO"}, {"_ParallaxMap","OreGold_Displ"} } },
            {"Ore_Obamium", new Dictionary<string, string>() { {"_MainTex","ore_Obamium_0"}, {"_BumpMap","OreGold_Norm"}, {"_OcclusionMap","OreGold_AO"}, {"_ParallaxMap","OreGold_Displ"} } },
            {"Planks", new Dictionary<string, string>() { {"_MainTex","WoodTexture"}, { "_BumpMap", "WoodTexture_NORMAL" } } },
            {"Rock", new Dictionary<string, string>() { {"_MainTex","RockTexture"} } },
            {"Scope", new Dictionary<string, string>() { {"_MainTex","ScopeTexture"} } },
            {"ShroomSus", new Dictionary<string, string>() { {"_MainTex","ShroomSus"} } },
            {"Stairs", new Dictionary<string, string>() { {"_MainTex","Stairs"} } },
            {"StoneGolem", new Dictionary<string, string>() { {"_MainTex","Ground026_2K_AmbientOcclusion"} } },
            {"Stylized Water 2", new Dictionary<string, string>() { {"_FoamTexture","CausticsDeep"} } },
            {"Tree", new Dictionary<string, string>() { {"_MainTex","TreeTexture"} } },
            {"Wheel2", new Dictionary<string, string>() { {"_OcclusionMap","Ground026_2K_Color"} } }
        };
    }
}
